### PR TITLE
json builder fails with missing file suffix

### PR DESCRIPTION
**Pull request by mmerickel**
See https://readthedocs.org/projects/pyramid/builds/3684682/

### CODE REVIEW

**Comment by mmerickel** [comment]
bump, can we get this released please

**Comment by mmerickel** [comment]
To be clear we can't build the Pyramid 1.5 docs without it.

**Comment by tseaver** [comment]
[Released](https://pypi.python.org/pypi/pylons_sphinx_latesturl/0.2)

**Comment by mmerickel** [comment]
Thanks. It took 3 tries on RTD but finally built successfully with the fix.

**Comment by tseaver** [comment]
Charming!

**Pull request merged**
